#!/bin/bash

### Put your own programs here.

# Workspace 1
exec "flatpak run com.github.iwalton3.jellyfin-media-player"

# Workspace 2
exec "/usr/lib64/discord/Discord"
exec swaymsg "workspace 2; exec firefox"

# Workspace 3
exec "steam"
exec "flatpak run com.heroicgameslauncher.hgl"

# Workspace 4

# Workspace 5
exec swaymsg "workspace 5; exec kitty"

# Workspace 6

# Workspace 7
exec "flatpak run md.obsidian.Obsidian"

# Workspace 8
exec "flatpak run com.vscodium.codium"

# Workspace 9
exec "$HOME/AppImages/Feishin*"
