#!/bin/bash

# Enable German Keyboard Layout
 input type:keyboard {
    xkb_layout "de"
 }

 input type:pointer {
    accel_profile "flat"
    pointer_accel -0.2
 }
# Enable Numlock
 input type:keyboard xkb_numlock disabled
