#!/bin/bash


# Enable XWayland
xwayland enable

# CONFIGURE THIS YOURSELF, AS I DO NOT KNOW YOUR MONITOR SETUP https://man.archlinux.org/man/sway.5.en#COMMANDS

### Output configuration

# Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
# Requires: desktop-backgrounds-compat, swaybg
output * background /home/marty/Pictures/wallpapers/wallpaper1.png fill
#
# Example configuration
#
output HDMI-A-1 resolution 1920x1080@60Hz position 0,0
output DP-1 resolution 2560x1440@143.912Hz position 1920,0
output DP-3 disable
#
# You can get the names of your outputs by running: swaymsg -t get_outputs, then order them accordingly with position, 0,0 is the top left of your setup.

