#!/bin/bash

# Gaps. The most important part
gaps inner 20
gaps outer 10
# Titlebar and Border shenanigans
default_border pixel 3
default_floating_border pixel
client.background n/a   $COLOR_BG n/a
client.focused          $COLOR_2 $COLOR_2 $COLOR_2 $COLOR_2 $COLOR_2
client.focused_inactive $COLOR_0 $COLOR_0 $COLOR_0 $COLOR_0
client.unfocused        $COLOR_0 $COLOR_0 $COLOR_0 $COLOR_0 $COLOR_0
client.urgent           $COLOR_1 $COLOR_1 $COLOR_1 $COLOR_1 $COLOR_1
smart_gaps off
smart_borders off

# Window assignation. This will make windows launch in set workspace by default.
# They can obviously be moved to any other workspace

# Workspace 1
assign [app_id="org.jellyfin.jellyfinmediaplayer"] workspace 1

# Workspace 2
assign [class="discord"] workspace 2

# Workspace 3
assign [class="steam"] workspace 3
assign [class="heroic"] workspace 3

# Workspace 4
assign [class="steam_app_*"] workspace 4
assign [app_id="yad"] workspace 4
assign [app_id="org.prismlauncher.PrismLauncher"] workspace 4
assign [class="Minecraft"] workspace 4
assign [app_id="moe.launcher.honkers-launcher"] workspace 4


# Workspace 5

# Workspace 6
assign [class="obsidian"] workspace 6

# Workspace 7
assign [class="VSCodium"] workspace 7

# Workspace 8
assign [app_id="Portmaster"] workspace 8

# Workspace 9
assign [class="Feishin"] workspace 9

### Window rules
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_type="menu"] floating enable
for_window [app_id="floating"] floating enable
for_window [app_id="floating_update"] floating enable, resize set width 1000px height 600px
for_window [app_id="Yad"] floating enable
for_window [app_id="yad"] floating enable
# https://github.com/ValveSoftware/steam-for-linux/issues/1040
for_window [class="^Steam$" title="^Friends$"] floating enable
for_window [class="^Steam$" title="Steam - News"] floating enable
for_window [class="^Steam$" title=".* - Chat"] floating enable
for_window [class="^Steam$" title="^Settings$"] floating enable
for_window [class="^Steam$" title=".* - event started"] floating enable
for_window [class="^Steam$" title=".* CD key"] floating enable
for_window [class="^Steam$" title="^Steam - Self Updater$"] floating enable
for_window [class="^Steam$" title="^Screenshot Uploader$"] floating enable
for_window [class="^Steam$" title="^Steam Guard - Computer Authorization Required$"] floating enable
for_window [title="^Steam Keyboard$"] floating enable
