#!/bin/bash

#workspace bananza
workspace 0 output HDMI-A-1
workspace 1 output HDMI-A-1
workspace 2 output DP-1
workspace 3 output DP-1
workspace 4 output DP-1
workspace 5 output DP-1
workspace 6 output DP-1
workspace 7 output DP-1
workspace 8 output DP-1
workspace 9 output DP-1

# Focus stops following mouse
focus_follows_mouse no
# Mouse won't move to output/window when changing focus
mouse_warping none
