#!/usr/bin/zsh

kitty +kitten themes Catppuccin-Mocha

touch "$HOME"/.config/kitty/mt_kitty.conf
curl https://raw.githubusercontent.com/martyTF/mt_tools/master/dotfiles/.config/kitty/kitty.conf > "$HOME"/.config/kitty/mt_kitty.conf

grep "include "$HOME"/.config/kitty/mt_kitty.conf" "$HOME"/.config/kitty/kitty.conf || echo "include "$HOME"/.config/kitty/mt_kitty.conf" >> "$HOME"/.config/kitty/kitty.conf
