#!/usr/bin/zsh

kitty +kitten themes Catppuccin-Mocha


        curl https://raw.githubusercontent.com/martyTF/mt_tools/master/configkitty | sh

        echo "include $HOME/.config/dotfiles/kitty/kitty.conf" >>~/.config/kitty/kitty.conf